// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qaypctbzvhhlrlsjmcwr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFheXBjdGJ6dmhobHJsc2ptY3dyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ3NDA1OTgsImV4cCI6MjA2MDMxNjU5OH0.yo_-sij_WogJ92wgFmvvw7tkGVykRX0iKzTckpMDHtI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);